POST http://localhost:8000/matches/2/commentary
Content-Type: application/json

{
  "minutes": 54,
  "sequence": 123,
  "period": "Second_Half",
  "eventType": "GOAL",
  "actor": "Raviteja",
  "team": "Barcelona FC",
  "message": "Wow! What a goal by Raviteja for Barcelona FC in the 54th minute of the second half!"
}
